use restaurant;

SELECT CUSTOMER.Customer_id, TOTAL_BILL.Bill_key
FROM CUSTOMER
INNER JOIN TOTAL_BILL
ON CUSTOMER.Customer_id=TOTAL_BILL.Customer_id
ORDER BY CUSTOMER.First_name;

SELECT CUSTOMER.First_name, HOME_DELIVERY.Delivery_id
FROM CUSTOMER
LEFT JOIN HOME_DELIVERY ON CUSTOMER.Customer_id = HOME_DELIVERY. Customer_id
ORDER BY CUSTOMER.First_name;

SELECT TOTAL_BILL.Bill_key, CUSTOMER.Customer_id
FROM CUSTOMER
RIGHT JOIN TOTAL_BILL ON CUSTOMER.Customer_id = TOTAL_BILL.Customer_id
ORDER BY Customer_Last_name;
